name: Deploy to Databricks

on:
  push:
    branches: [ main ]

env:
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN_DEV }}

jobs:
  deploy:
    name: Deploy Asset Bundle to Dev
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Databricks CLI
        run: pip install databricks-cli databricks-sdk

      - name: Configure DATABRICKS_HOST for Dev
        run: |
          echo "DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST_DEV }}" >> $GITHUB_ENV

      - name: Validate bundle
        run: databricks bundle validate --target dev

      - name: Deploy bundle
        run: databricks bundle deploy --target dev

      - name: Run bronze job
        run: databricks bundle run bronze-job --target dev

      - name: Run silver pipeline (DLT)
        run: databricks bundle run silver-pipeline --target dev

      - name: Run gold job
        run: databricks bundle run gold-job --target dev
